language: ruby

cache: bundler

sudo: required
before_script: "unset _JAVA_OPTIONS"
before_install: gem install bundler -v '<2'

rvm:
  - 2.5.3
  - 2.6.0
  - ruby-head

matrix:
  include:
    - rvm: 2.6.0
      script: bundle exec rake test_isolated
  include:
    - rvm: 2.6.0
      script: bundle exec rake rubocop
    - rvm: jruby-head
      env: JAVA_OPTS="--add-opens java.base/sun.nio.ch=org.jruby.dist --add-opens java.base/java.io=org.jruby.dist"
    - rvm: jruby-9.2.8.0
      env: JAVA_OPTS="--add-opens java.base/sun.nio.ch=org.jruby.dist --add-opens java.base/java.io=org.jruby.dist"
  allow_failures:
    - rvm: jruby-9.2.8.0
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "bJyiK4EXGfm0EhAId/QqIEdhPCx8BjxUKvx1h0+wgrsUm8BDoEN7tg2wqoGWU2KfzqLdx77wZVQXbmksOgmNcMGKJed5uNNMpAG4B+AQYTEX0odFRgOZKdkMtypga9CNIkKVgeSKhd6BY+g2AV6wvJ0Jq056uXpGkqK5OEFOpQc="
